# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Add workflow_dispatch for manual triggering
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to run against'
        required: true
        type: string
      reason:
        description: 'Reason for running'
        required: false
        default: 'Manual verification'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Conditional checkout based on trigger type
    - name: Checkout PR
      if: github.event_name == 'workflow_dispatch'
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.inputs.pr_number }}/head

    - name: Regular checkout
      if: github.event_name != 'workflow_dispatch'
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # Fetch and merge steps
    - name: Fetch all branches
      run: |
        git fetch --prune --unshallow
        git fetch origin ${GITHUB_BASE_REF:-master}
      env:
        GITHUB_BASE_REF: ${{ github.base_ref }}

    - name: Merge target branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge origin/${GITHUB_BASE_REF:-master} --no-edit
      env:
        GITHUB_BASE_REF: ${{ github.base_ref }}

    - name: Build
      run: go build -v ./...
      env:
        GO111MODULE: off
        GOPATH: ${{ github.workspace }}

    - name: Test
      run: go test -v ./...
      env:
        GO111MODULE: off
        GOPATH: ${{ github.workspace }}
